package com.sim.gls.jpa;
// Generated Feb 22, 2017 10:54:51 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private int categoryid;
     private String bankId;
     private String bocreatedby;
     private Date bodatecreated;
     private Date bodatemodified;
     private String bomodifiedby;
     private String categorycode;
     private String categorytype;
     private String categoryvalue;

    public Categories() {
    }

    public Categories(int categoryid, String bankId, String bocreatedby, Date bodatecreated, Date bodatemodified, String bomodifiedby, String categorycode, String categorytype, String categoryvalue) {
       this.categoryid = categoryid;
       this.bankId = bankId;
       this.bocreatedby = bocreatedby;
       this.bodatecreated = bodatecreated;
       this.bodatemodified = bodatemodified;
       this.bomodifiedby = bomodifiedby;
       this.categorycode = categorycode;
       this.categorytype = categorytype;
       this.categoryvalue = categoryvalue;
    }
   
    public int getCategoryid() {
        return this.categoryid;
    }
    
    public void setCategoryid(int categoryid) {
        this.categoryid = categoryid;
    }
    public String getBankId() {
        return this.bankId;
    }
    
    public void setBankId(String bankId) {
        this.bankId = bankId;
    }
    public String getBocreatedby() {
        return this.bocreatedby;
    }
    
    public void setBocreatedby(String bocreatedby) {
        this.bocreatedby = bocreatedby;
    }
    public Date getBodatecreated() {
        return this.bodatecreated;
    }
    
    public void setBodatecreated(Date bodatecreated) {
        this.bodatecreated = bodatecreated;
    }
    public Date getBodatemodified() {
        return this.bodatemodified;
    }
    
    public void setBodatemodified(Date bodatemodified) {
        this.bodatemodified = bodatemodified;
    }
    public String getBomodifiedby() {
        return this.bomodifiedby;
    }
    
    public void setBomodifiedby(String bomodifiedby) {
        this.bomodifiedby = bomodifiedby;
    }
    public String getCategorycode() {
        return this.categorycode;
    }
    
    public void setCategorycode(String categorycode) {
        this.categorycode = categorycode;
    }
    public String getCategorytype() {
        return this.categorytype;
    }
    
    public void setCategorytype(String categorytype) {
        this.categorytype = categorytype;
    }
    public String getCategoryvalue() {
        return this.categoryvalue;
    }
    
    public void setCategoryvalue(String categoryvalue) {
        this.categoryvalue = categoryvalue;
    }




}


