package com.sim.gls.jpa;
// Generated Feb 22, 2017 10:54:51 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CountryCodes generated by hbm2java
 */
public class CountryCodes  implements java.io.Serializable {


     private int countryId;
     private String countryCode;
     private String countryName;
     private String enabledFlg;
     private Date rcreTime;

    public CountryCodes() {
    }

    public CountryCodes(int countryId, String countryCode, String countryName, String enabledFlg, Date rcreTime) {
       this.countryId = countryId;
       this.countryCode = countryCode;
       this.countryName = countryName;
       this.enabledFlg = enabledFlg;
       this.rcreTime = rcreTime;
    }
   
    public int getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(int countryId) {
        this.countryId = countryId;
    }
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public String getCountryName() {
        return this.countryName;
    }
    
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }
    public String getEnabledFlg() {
        return this.enabledFlg;
    }
    
    public void setEnabledFlg(String enabledFlg) {
        this.enabledFlg = enabledFlg;
    }
    public Date getRcreTime() {
        return this.rcreTime;
    }
    
    public void setRcreTime(Date rcreTime) {
        this.rcreTime = rcreTime;
    }




}


