package com.sim.gls.jpa;
// Generated Feb 22, 2017 10:54:51 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CurrencyCodes generated by hbm2java
 */
public class CurrencyCodes  implements java.io.Serializable {


     private int currencyId;
     private String currencyCode;
     private String curerncyName;
     private String enabledFlg;
     private Date rcreTime;

    public CurrencyCodes() {
    }

    public CurrencyCodes(int currencyId, String currencyCode, String curerncyName, String enabledFlg, Date rcreTime) {
       this.currencyId = currencyId;
       this.currencyCode = currencyCode;
       this.curerncyName = curerncyName;
       this.enabledFlg = enabledFlg;
       this.rcreTime = rcreTime;
    }
   
    public int getCurrencyId() {
        return this.currencyId;
    }
    
    public void setCurrencyId(int currencyId) {
        this.currencyId = currencyId;
    }
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }
    public String getCurerncyName() {
        return this.curerncyName;
    }
    
    public void setCurerncyName(String curerncyName) {
        this.curerncyName = curerncyName;
    }
    public String getEnabledFlg() {
        return this.enabledFlg;
    }
    
    public void setEnabledFlg(String enabledFlg) {
        this.enabledFlg = enabledFlg;
    }
    public Date getRcreTime() {
        return this.rcreTime;
    }
    
    public void setRcreTime(Date rcreTime) {
        this.rcreTime = rcreTime;
    }




}


