package com.sim.gls.jpa;
// Generated Feb 22, 2017 10:54:51 AM by Hibernate Tools 4.3.1



/**
 * FinacleUsers generated by hbm2java
 */
public class FinacleUsers  implements java.io.Serializable {


     private String userName;
     private String solId;

    public FinacleUsers() {
    }

    public FinacleUsers(String userName, String solId) {
       this.userName = userName;
       this.solId = solId;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getSolId() {
        return this.solId;
    }
    
    public void setSolId(String solId) {
        this.solId = solId;
    }




}


