package com.sim.gls.jpa;
// Generated Feb 22, 2017 10:54:51 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GeneralAcctMastTable generated by hbm2java
 */
public class GeneralAcctMastTable implements java.io.Serializable {

    private String acid;
    private String acctCrncyCode;
    private String acctMgrUserId;
    private String acctName;
    private Date acctOpnDate;
    private String acctOwnership;
    private String bankId;
    private double clrBalAmt;
    private int custId;
    private String delFlg;
    private double drwngPower;
    private String entityCreFlg;
    private String foracid;
    private String groupId;
    private Date lastModifiedDate;
    private Date lchgTime;
    private String lchgUserId;
    private double lienAmt;
    private String mappedFlg;
    private Date rcreTime;
    private String rcreUserId;
    private double sanctLim;
    private String schmCode;
    private String schmType;
    private String solId;
    private String subGroupId;

    public GeneralAcctMastTable() {
    }
public GeneralAcctMastTable(String acctClassificationFlg, String acctClsFlg, String acctCrncyCode, String acctName, Date acctOpnDate, String acctOwnership, double clrBalAmt, double cumCrAmt, double cumDrAmt, int custId, String delFlg, double drwngPower, String entityCreFlg, String foracid, String frezCode, String glSubHeadCode, Date lastModifiedDate, Date lchgTime, String lchgUserId, double lienAmt, Date rcreTime, String rcreUserId, double sanctLim, String schmCode, String schmType, String solId, String systemOnlyAcctFlg, double wtaxPcnt) {
        this.acctCrncyCode = acctCrncyCode;
        this.acctName = acctName;
        this.acctOpnDate = acctOpnDate;
        this.acctOwnership = acctOwnership;
        this.clrBalAmt = clrBalAmt;
        this.custId = custId;
        this.delFlg = delFlg;
        this.drwngPower = drwngPower;
        this.entityCreFlg = entityCreFlg;
        this.foracid = foracid;
        this.lastModifiedDate = lastModifiedDate;
        this.lchgTime = lchgTime;
        this.lchgUserId = lchgUserId;
        this.lienAmt = lienAmt;
        this.rcreTime = rcreTime;
        this.rcreUserId = rcreUserId;
        this.sanctLim = sanctLim;
        this.schmCode = schmCode;
        this.schmType = schmType;
        this.solId = solId;
    }
    public GeneralAcctMastTable(String acid, String acctClassificationFlg, String acctClsFlg, String acctCrncyCode, String acctName, Date acctOpnDate, String acctOwnership, double clrBalAmt, double cumCrAmt, double cumDrAmt, int custId, String delFlg, double drwngPower, String entityCreFlg, String foracid, String frezCode, String glSubHeadCode, Date lastModifiedDate, Date lchgTime, String lchgUserId, double lienAmt, Date rcreTime, String rcreUserId, double sanctLim, String schmCode, String schmType, String solId, String systemOnlyAcctFlg, double wtaxPcnt) {
        this.acid = acid;
        this.acctCrncyCode = acctCrncyCode;
        this.acctName = acctName;
        this.acctOpnDate = acctOpnDate;
        this.acctOwnership = acctOwnership;
        this.clrBalAmt = clrBalAmt;
        this.custId = custId;
        this.delFlg = delFlg;
        this.drwngPower = drwngPower;
        this.entityCreFlg = entityCreFlg;
        this.foracid = foracid;
        this.lastModifiedDate = lastModifiedDate;
        this.lchgTime = lchgTime;
        this.lchgUserId = lchgUserId;
        this.lienAmt = lienAmt;
        this.rcreTime = rcreTime;
        this.rcreUserId = rcreUserId;
        this.sanctLim = sanctLim;
        this.schmCode = schmCode;
        this.schmType = schmType;
        this.solId = solId;
    }

    public GeneralAcctMastTable(String acid, String acctClassificationFlg, Date acctClsDate, String acctClsFlg, String acctCrncyCode, String acctMgrUserId, String acctName, Date acctOpnDate, String acctOwnership, String bankId, double clrBalAmt, double cumCrAmt, double cumDrAmt, int custId, String delFlg, double drwngPower, String entityCreFlg, String foracid, String frezCode, String glSubHeadCode, String groupId, String isLoanAgnstCltrlFlg, Date lastAnyTranDate, Date lastModifiedDate, Date lastTranDateCr, Date lastTranDateDr, Date lchgTime, String lchgUserId, double lienAmt, String mappedFlg, int operativeAcid, Date rcreTime, String rcreUserId, double sanctLim, String schmCode, String schmType, String solId, String subGroupId, String systemOnlyAcctFlg, double wtaxPcnt) {
        this.acid = acid;
        this.acctCrncyCode = acctCrncyCode;
        this.acctMgrUserId = acctMgrUserId;
        this.acctName = acctName;
        this.acctOpnDate = acctOpnDate;
        this.acctOwnership = acctOwnership;
        this.bankId = bankId;
        this.clrBalAmt = clrBalAmt;
        this.custId = custId;
        this.delFlg = delFlg;
        this.drwngPower = drwngPower;
        this.entityCreFlg = entityCreFlg;
        this.foracid = foracid;
        this.groupId = groupId;
        this.lastModifiedDate = lastModifiedDate;
        this.lchgTime = lchgTime;
        this.lchgUserId = lchgUserId;
        this.lienAmt = lienAmt;
        this.mappedFlg = mappedFlg;
        this.rcreTime = rcreTime;
        this.rcreUserId = rcreUserId;
        this.sanctLim = sanctLim;
        this.schmCode = schmCode;
        this.schmType = schmType;
        this.solId = solId;
        this.subGroupId = subGroupId;
    }

     
    public String getAcid() {
        return this.acid;
    }

    public void setAcid(String acid) {
        this.acid = acid;
    }

     
    public String getAcctCrncyCode() {
        return this.acctCrncyCode;
    }

    public void setAcctCrncyCode(String acctCrncyCode) {
        this.acctCrncyCode = acctCrncyCode;
    }

    
    public String getAcctMgrUserId() {
        return this.acctMgrUserId;
    }

    public void setAcctMgrUserId(String acctMgrUserId) {
        this.acctMgrUserId = acctMgrUserId;
    }

    
    public String getAcctName() {
        return this.acctName;
    }

    public void setAcctName(String acctName) {
        this.acctName = acctName;
    }

     public Date getAcctOpnDate() {
        return this.acctOpnDate;
    }

    public void setAcctOpnDate(Date acctOpnDate) {
        this.acctOpnDate = acctOpnDate;
    }

     
    public String getAcctOwnership() {
        return this.acctOwnership;
    }

    public void setAcctOwnership(String acctOwnership) {
        this.acctOwnership = acctOwnership;
    }

     
    public String getBankId() {
        return this.bankId;
    }

    public void setBankId(String bankId) {
        this.bankId = bankId;
    }

     
    public double getClrBalAmt() {
        return this.clrBalAmt;
    }

    public void setClrBalAmt(double clrBalAmt) {
        this.clrBalAmt = clrBalAmt;
    }

     
    public int getCustId() {
        return this.custId;
    }

    public void setCustId(int custId) {
        this.custId = custId;
    }

      
    public String getDelFlg() {
        return this.delFlg;
    }

    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

     
    public double getDrwngPower() {
        return this.drwngPower;
    }

    public void setDrwngPower(double drwngPower) {
        this.drwngPower = drwngPower;
    }

     
    public String getEntityCreFlg() {
        return this.entityCreFlg;
    }

    public void setEntityCreFlg(String entityCreFlg) {
        this.entityCreFlg = entityCreFlg;
    }

     
    public String getForacid() {
        return this.foracid;
    }

    public void setForacid(String foracid) {
        this.foracid = foracid;
    }

     
    public String getGroupId() {
        return this.groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

     public Date getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

     public Date getLchgTime() {
        return this.lchgTime;
    }

    public void setLchgTime(Date lchgTime) {
        this.lchgTime = lchgTime;
    }

  
    public String getLchgUserId() {
        return this.lchgUserId;
    }

    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId;
    }

   
    public double getLienAmt() {
        return this.lienAmt;
    }

    public void setLienAmt(double lienAmt) {
        this.lienAmt = lienAmt;
    }

    
    public String getMappedFlg() {
        return this.mappedFlg;
    }

    public void setMappedFlg(String mappedFlg) {
        this.mappedFlg = mappedFlg;
    }

     public Date getRcreTime() {
        return this.rcreTime;
    }

    public void setRcreTime(Date rcreTime) {
        this.rcreTime = rcreTime;
    }

     
    public String getRcreUserId() {
        return this.rcreUserId;
    }

    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId;
    }

     
    public double getSanctLim() {
        return this.sanctLim;
    }

    public void setSanctLim(double sanctLim) {
        this.sanctLim = sanctLim;
    }

     
    public String getSchmCode() {
        return this.schmCode;
    }

    public void setSchmCode(String schmCode) {
        this.schmCode = schmCode;
    }

     
    public String getSchmType() {
        return this.schmType;
    }

    public void setSchmType(String schmType) {
        this.schmType = schmType;
    }

     
    public String getSolId() {
        return this.solId;
    }

    public void setSolId(String solId) {
        this.solId = solId;
    }

     public String getSubGroupId() {
        return this.subGroupId;
    }

    public void setSubGroupId(String subGroupId) {
        this.subGroupId = subGroupId;
    }

}



