package com.sim.gls.jpa;
// Generated Feb 22, 2017 10:54:51 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GroupsTable generated by hbm2java
 */
public class GroupsTable  implements java.io.Serializable {


     private long groupId;
     private String bankId;
     private String branchName;
     private String countryCode;
     private String delFlg;
     private Date firstMeetDate;
     private Date formationDate;
     private String gpChair;
     private String gpRegion;
     private String gpSecretary;
     private String gpStatus;
     private String gpStatusCode;
     private String gpTreasurer;
     private String groupAddress;
     private String groupCenter;
     private String groupCode;
     private double groupLoans;
     private String groupName;
     private String groupPhone;
     private String groupType;
     private String groupVillage;
     private String grpMgrId;
     private String grpRegNo;
     private Date lchgDate;
     private String lchgUserId;
     private long loanAccounts;
     private long maxAllowedMembers;
     private long maxAllowedSubGrps;
     private String meetFrequency;
     private String meetPlace;
     private String meetTime;
     private long noOfMembers;
     private long noOfSubGrps;
     private Date nxtMeetDate;
     private double outstandingBal;
     private Date rcreTime;
     private String rcreUserId;
     private long savingAccounts;
     private double savingsAmt;
     private long solId;
     private Set subGrpTables = new HashSet(0);

    public GroupsTable() {
    }

     public GroupsTable(  String bankId, String branchName, String countryCode, String delFlg, Date firstMeetDate, Date formationDate, String gpRegion, String gpStatus, String gpStatusCode, String groupAddress, String groupCenter, String groupCode, double groupLoans, String groupName, String groupPhone, String groupType, String groupVillage, String grpMgrId, String grpRegNo, Date lchgDate, String lchgUserId, long loanAccounts, long maxAllowedMembers, long maxAllowedSubGrps, String meetFrequency, String meetPlace, long noOfMembers, long noOfSubGrps, Date nxtMeetDate, double outstandingBal, Date rcreTime, String rcreUserId, long savingAccounts, double savingsAmt, long solId) {
         this.bankId = bankId;
        this.branchName = branchName;
        this.countryCode = countryCode;
        this.delFlg = delFlg;
        this.firstMeetDate = firstMeetDate;
        this.formationDate = formationDate;
        this.gpRegion = gpRegion;
        this.gpStatus = gpStatus;
        this.gpStatusCode = gpStatusCode;
        this.groupAddress = groupAddress;
        this.groupCenter = groupCenter;
        this.groupCode = groupCode;
        this.groupLoans = groupLoans;
        this.groupName = groupName;
        this.groupPhone = groupPhone;
        this.groupType = groupType;
        this.groupVillage = groupVillage;
        this.grpMgrId = grpMgrId;
        this.grpRegNo = grpRegNo;
        this.lchgDate = lchgDate;
        this.lchgUserId = lchgUserId;
        this.loanAccounts = loanAccounts;
        this.maxAllowedMembers = maxAllowedMembers;
        this.maxAllowedSubGrps = maxAllowedSubGrps;
        this.meetFrequency = meetFrequency;
        this.meetPlace = meetPlace;
        this.noOfMembers = noOfMembers;
        this.noOfSubGrps = noOfSubGrps;
        this.nxtMeetDate = nxtMeetDate;
        this.outstandingBal = outstandingBal;
        this.rcreTime = rcreTime;
        this.rcreUserId = rcreUserId;
        this.savingAccounts = savingAccounts;
        this.savingsAmt = savingsAmt;
        this.solId = solId;
    }
	
    public GroupsTable(long groupId, String bankId, String branchName, String countryCode, String delFlg, Date firstMeetDate, Date formationDate, String gpRegion, String gpStatus, String gpStatusCode, String groupAddress, String groupCenter, String groupCode, double groupLoans, String groupName, String groupPhone, String groupType, String groupVillage, String grpMgrId, String grpRegNo, Date lchgDate, String lchgUserId, long loanAccounts, long maxAllowedMembers, long maxAllowedSubGrps, String meetFrequency, String meetPlace, long noOfMembers, long noOfSubGrps, Date nxtMeetDate, double outstandingBal, Date rcreTime, String rcreUserId, long savingAccounts, double savingsAmt, long solId) {
        this.groupId = groupId;
        this.bankId = bankId;
        this.branchName = branchName;
        this.countryCode = countryCode;
        this.delFlg = delFlg;
        this.firstMeetDate = firstMeetDate;
        this.formationDate = formationDate;
        this.gpRegion = gpRegion;
        this.gpStatus = gpStatus;
        this.gpStatusCode = gpStatusCode;
        this.groupAddress = groupAddress;
        this.groupCenter = groupCenter;
        this.groupCode = groupCode;
        this.groupLoans = groupLoans;
        this.groupName = groupName;
        this.groupPhone = groupPhone;
        this.groupType = groupType;
        this.groupVillage = groupVillage;
        this.grpMgrId = grpMgrId;
        this.grpRegNo = grpRegNo;
        this.lchgDate = lchgDate;
        this.lchgUserId = lchgUserId;
        this.loanAccounts = loanAccounts;
        this.maxAllowedMembers = maxAllowedMembers;
        this.maxAllowedSubGrps = maxAllowedSubGrps;
        this.meetFrequency = meetFrequency;
        this.meetPlace = meetPlace;
        this.noOfMembers = noOfMembers;
        this.noOfSubGrps = noOfSubGrps;
        this.nxtMeetDate = nxtMeetDate;
        this.outstandingBal = outstandingBal;
        this.rcreTime = rcreTime;
        this.rcreUserId = rcreUserId;
        this.savingAccounts = savingAccounts;
        this.savingsAmt = savingsAmt;
        this.solId = solId;
    }
    public GroupsTable(long groupId, String bankId, String branchName, String countryCode, String delFlg, Date firstMeetDate, Date formationDate, String gpChair, String gpRegion, String gpSecretary, String gpStatus, String gpStatusCode, String gpTreasurer, String groupAddress, String groupCenter, String groupCode, double groupLoans, String groupName, String groupPhone, String groupType, String groupVillage, String grpMgrId, String grpRegNo, Date lchgDate, String lchgUserId, long loanAccounts, long maxAllowedMembers, long maxAllowedSubGrps, String meetFrequency, String meetPlace, String meetTime, long noOfMembers, long noOfSubGrps, Date nxtMeetDate, double outstandingBal, Date rcreTime, String rcreUserId, long savingAccounts, double savingsAmt, long solId, Set subGrpTables) {
       this.groupId = groupId;
       this.bankId = bankId;
       this.branchName = branchName;
       this.countryCode = countryCode;
       this.delFlg = delFlg;
       this.firstMeetDate = firstMeetDate;
       this.formationDate = formationDate;
       this.gpChair = gpChair;
       this.gpRegion = gpRegion;
       this.gpSecretary = gpSecretary;
       this.gpStatus = gpStatus;
       this.gpStatusCode = gpStatusCode;
       this.gpTreasurer = gpTreasurer;
       this.groupAddress = groupAddress;
       this.groupCenter = groupCenter;
       this.groupCode = groupCode;
       this.groupLoans = groupLoans;
       this.groupName = groupName;
       this.groupPhone = groupPhone;
       this.groupType = groupType;
       this.groupVillage = groupVillage;
       this.grpMgrId = grpMgrId;
       this.grpRegNo = grpRegNo;
       this.lchgDate = lchgDate;
       this.lchgUserId = lchgUserId;
       this.loanAccounts = loanAccounts;
       this.maxAllowedMembers = maxAllowedMembers;
       this.maxAllowedSubGrps = maxAllowedSubGrps;
       this.meetFrequency = meetFrequency;
       this.meetPlace = meetPlace;
       this.meetTime = meetTime;
       this.noOfMembers = noOfMembers;
       this.noOfSubGrps = noOfSubGrps;
       this.nxtMeetDate = nxtMeetDate;
       this.outstandingBal = outstandingBal;
       this.rcreTime = rcreTime;
       this.rcreUserId = rcreUserId;
       this.savingAccounts = savingAccounts;
       this.savingsAmt = savingsAmt;
       this.solId = solId;
       this.subGrpTables = subGrpTables;
    }

    public GroupsTable(String bankId, String branchName, String countryCode, String delFlg, Date firstMeetDate, Date formationDate, String gpRegion, String gpStatus, String gpStatusCode, String groupAddress, String groupCenter, String groupCode, double groupLoans, String groupName, String groupPhone, String groupVillage, String grpMgrId, String grpRegNo, Date lchgDate, String lchgUserId, int loanAccounts, int maxAllowedMembers, int maxAllowedSubGrps, String meetFrequency, String meetPlace, int noOfMembers, int noOfSubGrps, Date nxtMeetDate, double outstandingBal, Date rcreTime, String rcreUserId, int savingAccounts, double savingsAmt, int solId) {
         this.bankId = bankId;
        this.branchName = branchName;
        this.countryCode = countryCode;
        this.delFlg = delFlg;
        this.firstMeetDate = firstMeetDate;
        this.formationDate = formationDate;
        this.gpRegion = gpRegion;
        this.gpStatus = gpStatus;
        this.gpStatusCode = gpStatusCode;
        this.groupAddress = groupAddress;
        this.groupCenter = groupCenter;
        this.groupCode = groupCode;
        this.groupLoans = groupLoans;
        this.groupName = groupName;
        this.groupPhone = groupPhone; 
        this.groupVillage = groupVillage;
        this.grpMgrId = grpMgrId;
        this.grpRegNo = grpRegNo;
        this.lchgDate = lchgDate;
        this.lchgUserId = lchgUserId;
        this.loanAccounts = loanAccounts;
        this.maxAllowedMembers = maxAllowedMembers;
        this.maxAllowedSubGrps = maxAllowedSubGrps;
        this.meetFrequency = meetFrequency;
        this.meetPlace = meetPlace;
        this.noOfMembers = noOfMembers;
        this.noOfSubGrps = noOfSubGrps;
        this.nxtMeetDate = nxtMeetDate;
        this.outstandingBal = outstandingBal;
        this.rcreTime = rcreTime;
        this.rcreUserId = rcreUserId;
        this.savingAccounts = savingAccounts;
        this.savingsAmt = savingsAmt;
        this.solId = solId; }
   
    public long getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(long groupId) {
        this.groupId = groupId;
    }
    public String getBankId() {
        return this.bankId;
    }
    
    public void setBankId(String bankId) {
        this.bankId = bankId;
    }
    public String getBranchName() {
        return this.branchName;
    }
    
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public String getDelFlg() {
        return this.delFlg;
    }
    
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }
    public Date getFirstMeetDate() {
        return this.firstMeetDate;
    }
    
    public void setFirstMeetDate(Date firstMeetDate) {
        this.firstMeetDate = firstMeetDate;
    }
    public Date getFormationDate() {
        return this.formationDate;
    }
    
    public void setFormationDate(Date formationDate) {
        this.formationDate = formationDate;
    }
    public String getGpChair() {
        return this.gpChair;
    }
    
    public void setGpChair(String gpChair) {
        this.gpChair = gpChair;
    }
    public String getGpRegion() {
        return this.gpRegion;
    }
    
    public void setGpRegion(String gpRegion) {
        this.gpRegion = gpRegion;
    }
    public String getGpSecretary() {
        return this.gpSecretary;
    }
    
    public void setGpSecretary(String gpSecretary) {
        this.gpSecretary = gpSecretary;
    }
    public String getGpStatus() {
        return this.gpStatus;
    }
    
    public void setGpStatus(String gpStatus) {
        this.gpStatus = gpStatus;
    }
    public String getGpStatusCode() {
        return this.gpStatusCode;
    }
    
    public void setGpStatusCode(String gpStatusCode) {
        this.gpStatusCode = gpStatusCode;
    }
    public String getGpTreasurer() {
        return this.gpTreasurer;
    }
    
    public void setGpTreasurer(String gpTreasurer) {
        this.gpTreasurer = gpTreasurer;
    }
    public String getGroupAddress() {
        return this.groupAddress;
    }
    
    public void setGroupAddress(String groupAddress) {
        this.groupAddress = groupAddress;
    }
    public String getGroupCenter() {
        return this.groupCenter;
    }
    
    public void setGroupCenter(String groupCenter) {
        this.groupCenter = groupCenter;
    }
    public String getGroupCode() {
        return this.groupCode;
    }
    
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }
    public double getGroupLoans() {
        return this.groupLoans;
    }
    
    public void setGroupLoans(double groupLoans) {
        this.groupLoans = groupLoans;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public String getGroupPhone() {
        return this.groupPhone;
    }
    
    public void setGroupPhone(String groupPhone) {
        this.groupPhone = groupPhone;
    }
    public String getGroupType() {
        return this.groupType;
    }
    
    public void setGroupType(String groupType) {
        this.groupType = groupType;
    }
    public String getGroupVillage() {
        return this.groupVillage;
    }
    
    public void setGroupVillage(String groupVillage) {
        this.groupVillage = groupVillage;
    }
    public String getGrpMgrId() {
        return this.grpMgrId;
    }
    
    public void setGrpMgrId(String grpMgrId) {
        this.grpMgrId = grpMgrId;
    }
    public String getGrpRegNo() {
        return this.grpRegNo;
    }
    
    public void setGrpRegNo(String grpRegNo) {
        this.grpRegNo = grpRegNo;
    }
    public Date getLchgDate() {
        return this.lchgDate;
    }
    
    public void setLchgDate(Date lchgDate) {
        this.lchgDate = lchgDate;
    }
    public String getLchgUserId() {
        return this.lchgUserId;
    }
    
    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId;
    }
    public long getLoanAccounts() {
        return this.loanAccounts;
    }
    
    public void setLoanAccounts(long loanAccounts) {
        this.loanAccounts = loanAccounts;
    }
    public long getMaxAllowedMembers() {
        return this.maxAllowedMembers;
    }
    
    public void setMaxAllowedMembers(long maxAllowedMembers) {
        this.maxAllowedMembers = maxAllowedMembers;
    }
    public long getMaxAllowedSubGrps() {
        return this.maxAllowedSubGrps;
    }
    
    public void setMaxAllowedSubGrps(long maxAllowedSubGrps) {
        this.maxAllowedSubGrps = maxAllowedSubGrps;
    }
    public String getMeetFrequency() {
        return this.meetFrequency;
    }
    
    public void setMeetFrequency(String meetFrequency) {
        this.meetFrequency = meetFrequency;
    }
    public String getMeetPlace() {
        return this.meetPlace;
    }
    
    public void setMeetPlace(String meetPlace) {
        this.meetPlace = meetPlace;
    }
    public String getMeetTime() {
        return this.meetTime;
    }
    
    public void setMeetTime(String meetTime) {
        this.meetTime = meetTime;
    }
    public long getNoOfMembers() {
        return this.noOfMembers;
    }
    
    public void setNoOfMembers(long noOfMembers) {
        this.noOfMembers = noOfMembers;
    }
    public long getNoOfSubGrps() {
        return this.noOfSubGrps;
    }
    
    public void setNoOfSubGrps(long noOfSubGrps) {
        this.noOfSubGrps = noOfSubGrps;
    }
    public Date getNxtMeetDate() {
        return this.nxtMeetDate;
    }
    
    public void setNxtMeetDate(Date nxtMeetDate) {
        this.nxtMeetDate = nxtMeetDate;
    }
    public double getOutstandingBal() {
        return this.outstandingBal;
    }
    
    public void setOutstandingBal(double outstandingBal) {
        this.outstandingBal = outstandingBal;
    }
    public Date getRcreTime() {
        return this.rcreTime;
    }
    
    public void setRcreTime(Date rcreTime) {
        this.rcreTime = rcreTime;
    }
    public String getRcreUserId() {
        return this.rcreUserId;
    }
    
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId;
    }
    public long getSavingAccounts() {
        return this.savingAccounts;
    }
    
    public void setSavingAccounts(long savingAccounts) {
        this.savingAccounts = savingAccounts;
    }
    public double getSavingsAmt() {
        return this.savingsAmt;
    }
    
    public void setSavingsAmt(double savingsAmt) {
        this.savingsAmt = savingsAmt;
    }
    public long getSolId() {
        return this.solId;
    }
    
    public void setSolId(long solId) {
        this.solId = solId;
    }
    public Set getSubGrpTables() {
        return this.subGrpTables;
    }
    
    public void setSubGrpTables(Set subGrpTables) {
        this.subGrpTables = subGrpTables;
    }




}


