package com.sim.gls.jpa;
// Generated Feb 22, 2017 10:54:51 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * HistoryTransactionsTable generated by hbm2java
 */
public class HistoryTransactionsTable  implements java.io.Serializable {


     private long tranId;
     private String foracid;
     private String bankTranId;
     private String delFlg;
     private Date lchgTime;
     private String lchgUserId;
     private String pstdFlg;
     private Date rcreTime;
     private String rcreUserId;
     private String subGroupCode;
     private BigDecimal tranAmt;
     private Date tranDate;
     private String tranParticulars;
     private String tranType;

    public HistoryTransactionsTable() {
    }

	
    public HistoryTransactionsTable(long tranId) {
        this.tranId = tranId;
    }
    public HistoryTransactionsTable(long tranId, String foracid, String bankTranId, String delFlg, Date lchgTime, String lchgUserId, String pstdFlg, Date rcreTime, String rcreUserId, String subGroupCode, BigDecimal tranAmt, Date tranDate, String tranParticulars, String tranType) {
       this.tranId = tranId;
       this.foracid = foracid;
       this.bankTranId = bankTranId;
       this.delFlg = delFlg;
       this.lchgTime = lchgTime;
       this.lchgUserId = lchgUserId;
       this.pstdFlg = pstdFlg;
       this.rcreTime = rcreTime;
       this.rcreUserId = rcreUserId;
       this.subGroupCode = subGroupCode;
       this.tranAmt = tranAmt;
       this.tranDate = tranDate;
       this.tranParticulars = tranParticulars;
       this.tranType = tranType;
    }
   
    public long getTranId() {
        return this.tranId;
    }
    
    public void setTranId(long tranId) {
        this.tranId = tranId;
    }
    public String getForacid() {
        return this.foracid;
    }
    
    public void setForacid(String foracid) {
        this.foracid = foracid;
    }
    public String getBankTranId() {
        return this.bankTranId;
    }
    
    public void setBankTranId(String bankTranId) {
        this.bankTranId = bankTranId;
    }
    public String getDelFlg() {
        return this.delFlg;
    }
    
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }
    public Date getLchgTime() {
        return this.lchgTime;
    }
    
    public void setLchgTime(Date lchgTime) {
        this.lchgTime = lchgTime;
    }
    public String getLchgUserId() {
        return this.lchgUserId;
    }
    
    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId;
    }
    public String getPstdFlg() {
        return this.pstdFlg;
    }
    
    public void setPstdFlg(String pstdFlg) {
        this.pstdFlg = pstdFlg;
    }
    public Date getRcreTime() {
        return this.rcreTime;
    }
    
    public void setRcreTime(Date rcreTime) {
        this.rcreTime = rcreTime;
    }
    public String getRcreUserId() {
        return this.rcreUserId;
    }
    
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId;
    }
    public String getSubGroupCode() {
        return this.subGroupCode;
    }
    
    public void setSubGroupCode(String subGroupCode) {
        this.subGroupCode = subGroupCode;
    }
    public BigDecimal getTranAmt() {
        return this.tranAmt;
    }
    
    public void setTranAmt(BigDecimal tranAmt) {
        this.tranAmt = tranAmt;
    }
    public Date getTranDate() {
        return this.tranDate;
    }
    
    public void setTranDate(Date tranDate) {
        this.tranDate = tranDate;
    }
    public String getTranParticulars() {
        return this.tranParticulars;
    }
    
    public void setTranParticulars(String tranParticulars) {
        this.tranParticulars = tranParticulars;
    }
    public String getTranType() {
        return this.tranType;
    }
    
    public void setTranType(String tranType) {
        this.tranType = tranType;
    }




}


