package com.sim.gls.jpa;
// Generated May 5, 2016 4:34:06 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Justinewachira generated by hbm2java
 */
@Entity
@Table(name="JUSTINEWACHIRA"
    ,schema="GLS"
)
public class Justinewachira  implements java.io.Serializable {


     private int justId;
     private String justName;
     private int justAge;
     private double accountBalance;

    public Justinewachira() {
    }

    public Justinewachira(String justName, int justAge, double accountBalance) {
       this.justName = justName;
       this.justAge = justAge;
       this.accountBalance = accountBalance;
    }
   
     @Id 

    @GeneratedValue
    @Column(name="JUST_ID", unique=true, nullable=false, precision=22, scale=0)
    public int getJustId() {
        return this.justId;
    }
    
    public void setJustId(int justId) {
        this.justId = justId;
    }

    
    @Column(name="JUST_NAME", nullable=false, length=30)
    public String getJustName() {
        return this.justName;
    }
    
    public void setJustName(String justName) {
        this.justName = justName;
    }

    
    @Column(name="JUST_AGE", nullable=false, precision=22, scale=0)
    public int getJustAge() {
        return this.justAge;
    }
    
    public void setJustAge(int justAge) {
        this.justAge = justAge;
    }

    
    @Column(name="ACCOUNT_BALANCE", nullable=false, precision=22, scale=0)
    public double getAccountBalance() {
        return this.accountBalance;
    }
    
    public void setAccountBalance(double accountBalance) {
        this.accountBalance = accountBalance;
    }




}


