package com.sim.gls.jpa;
// Generated Feb 22, 2017 10:54:51 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * LaAmortShdlTableReport generated by hbm2java
 */
public class LaAmortShdlTableReport  implements java.io.Serializable {


     private BigDecimal acid;
     private double adjInt;
     private double adjPrinc;
     private BigDecimal amortId;
     private String bankId;
     private double expcBal;
     private Date flowDate;
     private double intDmd;
     private long paymentIndex;
     private double princDmd;

    public LaAmortShdlTableReport() {
    }

    public LaAmortShdlTableReport(BigDecimal acid, double adjInt, double adjPrinc, BigDecimal amortId, String bankId, double expcBal, Date flowDate, double intDmd, long paymentIndex, double princDmd) {
       this.acid = acid;
       this.adjInt = adjInt;
       this.adjPrinc = adjPrinc;
       this.amortId = amortId;
       this.bankId = bankId;
       this.expcBal = expcBal;
       this.flowDate = flowDate;
       this.intDmd = intDmd;
       this.paymentIndex = paymentIndex;
       this.princDmd = princDmd;
    }
   
    public BigDecimal getAcid() {
        return this.acid;
    }
    
    public void setAcid(BigDecimal acid) {
        this.acid = acid;
    }
    public double getAdjInt() {
        return this.adjInt;
    }
    
    public void setAdjInt(double adjInt) {
        this.adjInt = adjInt;
    }
    public double getAdjPrinc() {
        return this.adjPrinc;
    }
    
    public void setAdjPrinc(double adjPrinc) {
        this.adjPrinc = adjPrinc;
    }
    public BigDecimal getAmortId() {
        return this.amortId;
    }
    
    public void setAmortId(BigDecimal amortId) {
        this.amortId = amortId;
    }
    public String getBankId() {
        return this.bankId;
    }
    
    public void setBankId(String bankId) {
        this.bankId = bankId;
    }
    public double getExpcBal() {
        return this.expcBal;
    }
    
    public void setExpcBal(double expcBal) {
        this.expcBal = expcBal;
    }
    public Date getFlowDate() {
        return this.flowDate;
    }
    
    public void setFlowDate(Date flowDate) {
        this.flowDate = flowDate;
    }
    public double getIntDmd() {
        return this.intDmd;
    }
    
    public void setIntDmd(double intDmd) {
        this.intDmd = intDmd;
    }
    public long getPaymentIndex() {
        return this.paymentIndex;
    }
    
    public void setPaymentIndex(long paymentIndex) {
        this.paymentIndex = paymentIndex;
    }
    public double getPrincDmd() {
        return this.princDmd;
    }
    
    public void setPrincDmd(double princDmd) {
        this.princDmd = princDmd;
    }




}


