package com.sim.gls.jpa;
// Generated Feb 22, 2017 10:54:51 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * LaTranDetailTable generated by hbm2java
 */
public class LaTranDetailTable  implements java.io.Serializable {


     private BigDecimal tranId;
     private BigDecimal accountNo;
     private String delFlg;
     private Date lchgTime;
     private String lchgUserId;
     private Date rcreTime;
     private String rcreUserId;
     private String subTranType;
     private BigDecimal tranAmt;
     private Date tranDate;
     private Date valueDate;

    public LaTranDetailTable() {
    }

    public LaTranDetailTable(BigDecimal tranId, BigDecimal accountNo, String delFlg, Date lchgTime, String lchgUserId, Date rcreTime, String rcreUserId, String subTranType, BigDecimal tranAmt, Date tranDate, Date valueDate) {
       this.tranId = tranId;
       this.accountNo = accountNo;
       this.delFlg = delFlg;
       this.lchgTime = lchgTime;
       this.lchgUserId = lchgUserId;
       this.rcreTime = rcreTime;
       this.rcreUserId = rcreUserId;
       this.subTranType = subTranType;
       this.tranAmt = tranAmt;
       this.tranDate = tranDate;
       this.valueDate = valueDate;
    }
   
    public BigDecimal getTranId() {
        return this.tranId;
    }
    
    public void setTranId(BigDecimal tranId) {
        this.tranId = tranId;
    }
    public BigDecimal getAccountNo() {
        return this.accountNo;
    }
    
    public void setAccountNo(BigDecimal accountNo) {
        this.accountNo = accountNo;
    }
    public String getDelFlg() {
        return this.delFlg;
    }
    
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }
    public Date getLchgTime() {
        return this.lchgTime;
    }
    
    public void setLchgTime(Date lchgTime) {
        this.lchgTime = lchgTime;
    }
    public String getLchgUserId() {
        return this.lchgUserId;
    }
    
    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId;
    }
    public Date getRcreTime() {
        return this.rcreTime;
    }
    
    public void setRcreTime(Date rcreTime) {
        this.rcreTime = rcreTime;
    }
    public String getRcreUserId() {
        return this.rcreUserId;
    }
    
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId;
    }
    public String getSubTranType() {
        return this.subTranType;
    }
    
    public void setSubTranType(String subTranType) {
        this.subTranType = subTranType;
    }
    public BigDecimal getTranAmt() {
        return this.tranAmt;
    }
    
    public void setTranAmt(BigDecimal tranAmt) {
        this.tranAmt = tranAmt;
    }
    public Date getTranDate() {
        return this.tranDate;
    }
    
    public void setTranDate(Date tranDate) {
        this.tranDate = tranDate;
    }
    public Date getValueDate() {
        return this.valueDate;
    }
    
    public void setValueDate(Date valueDate) {
        this.valueDate = valueDate;
    }




}


