package com.sim.gls.jpa;
// Generated Feb 22, 2017 10:54:51 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * LoanDemandsTable generated by hbm2java
 */
public class LoanDemandsTable  implements java.io.Serializable {


     private String acid;
     private BigDecimal dmdAmt;
     private Date dmdDate;
     private String status;

    public LoanDemandsTable() {
    }

	
    public LoanDemandsTable(String acid) {
        this.acid = acid;
    }
    public LoanDemandsTable(String acid, BigDecimal dmdAmt, Date dmdDate, String status) {
       this.acid = acid;
       this.dmdAmt = dmdAmt;
       this.dmdDate = dmdDate;
       this.status = status;
    }
   
    public String getAcid() {
        return this.acid;
    }
    
    public void setAcid(String acid) {
        this.acid = acid;
    }
    public BigDecimal getDmdAmt() {
        return this.dmdAmt;
    }
    
    public void setDmdAmt(BigDecimal dmdAmt) {
        this.dmdAmt = dmdAmt;
    }
    public Date getDmdDate() {
        return this.dmdDate;
    }
    
    public void setDmdDate(Date dmdDate) {
        this.dmdDate = dmdDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


