package com.sim.gls.jpa;
// Generated Feb 22, 2017 10:54:51 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * LoanDetailsTable generated by hbm2java
 */
public class LoanDetailsTable  implements java.io.Serializable {


     private String acid;
     private Double disAmt;
     private Date disShdlDate;
     private BigDecimal numAdvanceInstlmnt;
     private Double rephasementPrincipal;
     private Double upfrontInstlAmt;

    public LoanDetailsTable() {
    }

	
    public LoanDetailsTable(String acid) {
        this.acid = acid;
    }
    public LoanDetailsTable(String acid, Double disAmt, Date disShdlDate, BigDecimal numAdvanceInstlmnt, Double rephasementPrincipal, Double upfrontInstlAmt) {
       this.acid = acid;
       this.disAmt = disAmt;
       this.disShdlDate = disShdlDate;
       this.numAdvanceInstlmnt = numAdvanceInstlmnt;
       this.rephasementPrincipal = rephasementPrincipal;
       this.upfrontInstlAmt = upfrontInstlAmt;
    }
   
    public String getAcid() {
        return this.acid;
    }
    
    public void setAcid(String acid) {
        this.acid = acid;
    }
    public Double getDisAmt() {
        return this.disAmt;
    }
    
    public void setDisAmt(Double disAmt) {
        this.disAmt = disAmt;
    }
    public Date getDisShdlDate() {
        return this.disShdlDate;
    }
    
    public void setDisShdlDate(Date disShdlDate) {
        this.disShdlDate = disShdlDate;
    }
    public BigDecimal getNumAdvanceInstlmnt() {
        return this.numAdvanceInstlmnt;
    }
    
    public void setNumAdvanceInstlmnt(BigDecimal numAdvanceInstlmnt) {
        this.numAdvanceInstlmnt = numAdvanceInstlmnt;
    }
    public Double getRephasementPrincipal() {
        return this.rephasementPrincipal;
    }
    
    public void setRephasementPrincipal(Double rephasementPrincipal) {
        this.rephasementPrincipal = rephasementPrincipal;
    }
    public Double getUpfrontInstlAmt() {
        return this.upfrontInstlAmt;
    }
    
    public void setUpfrontInstlAmt(Double upfrontInstlAmt) {
        this.upfrontInstlAmt = upfrontInstlAmt;
    }




}


