package com.sim.gls.jpa;
// Generated Feb 22, 2017 10:54:51 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LoggedInUser generated by hbm2java
 */
public class LoggedInUser  implements java.io.Serializable {


     private long logId;
     private Date loggedInTime;
     private String sessionId;
     private String solId;
     private String userName;

    public LoggedInUser() {
    }

	
    public LoggedInUser(long logId, Date loggedInTime, String solId, String userName) {
        this.logId = logId;
        this.loggedInTime = loggedInTime;
        this.solId = solId;
        this.userName = userName;
    }
    public LoggedInUser(long logId, Date loggedInTime, String sessionId, String solId, String userName) {
       this.logId = logId;
       this.loggedInTime = loggedInTime;
       this.sessionId = sessionId;
       this.solId = solId;
       this.userName = userName;
    }
   
    public long getLogId() {
        return this.logId;
    }
    
    public void setLogId(long logId) {
        this.logId = logId;
    }
    public Date getLoggedInTime() {
        return this.loggedInTime;
    }
    
    public void setLoggedInTime(Date loggedInTime) {
        this.loggedInTime = loggedInTime;
    }
    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }
    public String getSolId() {
        return this.solId;
    }
    
    public void setSolId(String solId) {
        this.solId = solId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }




}


