package com.sim.gls.jpa;
// Generated Feb 22, 2017 10:54:51 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RegionsTableMod generated by hbm2java
 */
public class RegionsTableMod  implements java.io.Serializable {


     private long modId;
     private String bankId;
     private String countryCode;
     private String delFlg;
     private Date rcreTime;
     private String rcreUserId;
     private long regionId;
     private String regionName;

    public RegionsTableMod() {
    }

    public RegionsTableMod(long modId, String bankId, String countryCode, String delFlg, Date rcreTime, String rcreUserId, long regionId, String regionName) {
       this.modId = modId;
       this.bankId = bankId;
       this.countryCode = countryCode;
       this.delFlg = delFlg;
       this.rcreTime = rcreTime;
       this.rcreUserId = rcreUserId;
       this.regionId = regionId;
       this.regionName = regionName;
    }
   
    public long getModId() {
        return this.modId;
    }
    
    public void setModId(long modId) {
        this.modId = modId;
    }
    public String getBankId() {
        return this.bankId;
    }
    
    public void setBankId(String bankId) {
        this.bankId = bankId;
    }
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public String getDelFlg() {
        return this.delFlg;
    }
    
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }
    public Date getRcreTime() {
        return this.rcreTime;
    }
    
    public void setRcreTime(Date rcreTime) {
        this.rcreTime = rcreTime;
    }
    public String getRcreUserId() {
        return this.rcreUserId;
    }
    
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId;
    }
    public long getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(long regionId) {
        this.regionId = regionId;
    }
    public String getRegionName() {
        return this.regionName;
    }
    
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }




}


