package com.sim.gls.jpa;
// Generated Feb 22, 2017 10:54:51 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ResMapping generated by hbm2java
 */
public class ResMapping  implements java.io.Serializable {


     private long mapId;
     private String delFlg;
     private String mopId;
     private String mopText;
     private String mopUrl;
     private String rcreRep;
     private Date rcreTime;
     private String rcreUser;
     private long resId;
     private String roleName;

    public ResMapping() {
    }

	
    public ResMapping(long mapId, String delFlg, String mopId, String mopText, String mopUrl, Date rcreTime, String rcreUser, long resId, String roleName) {
        this.mapId = mapId;
        this.delFlg = delFlg;
        this.mopId = mopId;
        this.mopText = mopText;
        this.mopUrl = mopUrl;
        this.rcreTime = rcreTime;
        this.rcreUser = rcreUser;
        this.resId = resId;
        this.roleName = roleName;
    }
    public ResMapping(long mapId, String delFlg, String mopId, String mopText, String mopUrl, String rcreRep, Date rcreTime, String rcreUser, long resId, String roleName) {
       this.mapId = mapId;
       this.delFlg = delFlg;
       this.mopId = mopId;
       this.mopText = mopText;
       this.mopUrl = mopUrl;
       this.rcreRep = rcreRep;
       this.rcreTime = rcreTime;
       this.rcreUser = rcreUser;
       this.resId = resId;
       this.roleName = roleName;
    }
   
    public long getMapId() {
        return this.mapId;
    }
    
    public void setMapId(long mapId) {
        this.mapId = mapId;
    }
    public String getDelFlg() {
        return this.delFlg;
    }
    
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }
    public String getMopId() {
        return this.mopId;
    }
    
    public void setMopId(String mopId) {
        this.mopId = mopId;
    }
    public String getMopText() {
        return this.mopText;
    }
    
    public void setMopText(String mopText) {
        this.mopText = mopText;
    }
    public String getMopUrl() {
        return this.mopUrl;
    }
    
    public void setMopUrl(String mopUrl) {
        this.mopUrl = mopUrl;
    }
    public String getRcreRep() {
        return this.rcreRep;
    }
    
    public void setRcreRep(String rcreRep) {
        this.rcreRep = rcreRep;
    }
    public Date getRcreTime() {
        return this.rcreTime;
    }
    
    public void setRcreTime(Date rcreTime) {
        this.rcreTime = rcreTime;
    }
    public String getRcreUser() {
        return this.rcreUser;
    }
    
    public void setRcreUser(String rcreUser) {
        this.rcreUser = rcreUser;
    }
    public long getResId() {
        return this.resId;
    }
    
    public void setResId(long resId) {
        this.resId = resId;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }




}


