package com.sim.gls.jpa;
// Generated Feb 22, 2017 10:54:51 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Resources generated by hbm2java
 */
public class Resources  implements java.io.Serializable {


     private long resId;
     private String mopId;
     private String mopText;
     private String mopUrl;
     private String rcreRep;
     private Date rcreTime;
     private String rcreUser;

    public Resources() {
    }

	
    public Resources(long resId, String mopId, String mopText, String mopUrl, Date rcreTime, String rcreUser) {
        this.resId = resId;
        this.mopId = mopId;
        this.mopText = mopText;
        this.mopUrl = mopUrl;
        this.rcreTime = rcreTime;
        this.rcreUser = rcreUser;
    }
    public Resources(long resId, String mopId, String mopText, String mopUrl, String rcreRep, Date rcreTime, String rcreUser) {
       this.resId = resId;
       this.mopId = mopId;
       this.mopText = mopText;
       this.mopUrl = mopUrl;
       this.rcreRep = rcreRep;
       this.rcreTime = rcreTime;
       this.rcreUser = rcreUser;
    }
   
    public long getResId() {
        return this.resId;
    }
    
    public void setResId(long resId) {
        this.resId = resId;
    }
    public String getMopId() {
        return this.mopId;
    }
    
    public void setMopId(String mopId) {
        this.mopId = mopId;
    }
    public String getMopText() {
        return this.mopText;
    }
    
    public void setMopText(String mopText) {
        this.mopText = mopText;
    }
    public String getMopUrl() {
        return this.mopUrl;
    }
    
    public void setMopUrl(String mopUrl) {
        this.mopUrl = mopUrl;
    }
    public String getRcreRep() {
        return this.rcreRep;
    }
    
    public void setRcreRep(String rcreRep) {
        this.rcreRep = rcreRep;
    }
    public Date getRcreTime() {
        return this.rcreTime;
    }
    
    public void setRcreTime(Date rcreTime) {
        this.rcreTime = rcreTime;
    }
    public String getRcreUser() {
        return this.rcreUser;
    }
    
    public void setRcreUser(String rcreUser) {
        this.rcreUser = rcreUser;
    }




}


