package com.sim.gls.jpa;
// Generated Feb 22, 2017 10:54:51 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RoleCrncyLimitTableMod generated by hbm2java
 */
public class RoleCrncyLimitTableMod  implements java.io.Serializable {


     private long modId;
     private String bankId;
     private String crncyCode;
     private String delFlg;
     private Date lchgDate;
     private long limitId;
     private Date rcreTime;
     private String roleId;
     private double userCashDrLim;
     private double userIntersolCashDrLimit;
     private double userIntersolXferDrLimit;
     private double userXferDrLim;

    public RoleCrncyLimitTableMod() {
    }

    public RoleCrncyLimitTableMod(long modId, String bankId, String crncyCode, String delFlg, Date lchgDate, long limitId, Date rcreTime, String roleId, double userCashDrLim, double userIntersolCashDrLimit, double userIntersolXferDrLimit, double userXferDrLim) {
       this.modId = modId;
       this.bankId = bankId;
       this.crncyCode = crncyCode;
       this.delFlg = delFlg;
       this.lchgDate = lchgDate;
       this.limitId = limitId;
       this.rcreTime = rcreTime;
       this.roleId = roleId;
       this.userCashDrLim = userCashDrLim;
       this.userIntersolCashDrLimit = userIntersolCashDrLimit;
       this.userIntersolXferDrLimit = userIntersolXferDrLimit;
       this.userXferDrLim = userXferDrLim;
    }
   
    public long getModId() {
        return this.modId;
    }
    
    public void setModId(long modId) {
        this.modId = modId;
    }
    public String getBankId() {
        return this.bankId;
    }
    
    public void setBankId(String bankId) {
        this.bankId = bankId;
    }
    public String getCrncyCode() {
        return this.crncyCode;
    }
    
    public void setCrncyCode(String crncyCode) {
        this.crncyCode = crncyCode;
    }
    public String getDelFlg() {
        return this.delFlg;
    }
    
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }
    public Date getLchgDate() {
        return this.lchgDate;
    }
    
    public void setLchgDate(Date lchgDate) {
        this.lchgDate = lchgDate;
    }
    public long getLimitId() {
        return this.limitId;
    }
    
    public void setLimitId(long limitId) {
        this.limitId = limitId;
    }
    public Date getRcreTime() {
        return this.rcreTime;
    }
    
    public void setRcreTime(Date rcreTime) {
        this.rcreTime = rcreTime;
    }
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    public double getUserCashDrLim() {
        return this.userCashDrLim;
    }
    
    public void setUserCashDrLim(double userCashDrLim) {
        this.userCashDrLim = userCashDrLim;
    }
    public double getUserIntersolCashDrLimit() {
        return this.userIntersolCashDrLimit;
    }
    
    public void setUserIntersolCashDrLimit(double userIntersolCashDrLimit) {
        this.userIntersolCashDrLimit = userIntersolCashDrLimit;
    }
    public double getUserIntersolXferDrLimit() {
        return this.userIntersolXferDrLimit;
    }
    
    public void setUserIntersolXferDrLimit(double userIntersolXferDrLimit) {
        this.userIntersolXferDrLimit = userIntersolXferDrLimit;
    }
    public double getUserXferDrLim() {
        return this.userXferDrLim;
    }
    
    public void setUserXferDrLim(double userXferDrLim) {
        this.userXferDrLim = userXferDrLim;
    }




}


