package com.sim.gls.jpa;
// Generated Feb 22, 2017 10:54:51 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SolGroupControlTableMod generated by hbm2java
 */
public class SolGroupControlTableMod  implements java.io.Serializable {


     private long solGroupId;
     private long modId;
     private String bankId;
     private Date dbStatDate;
     private Date dcClsDate;
     private String dcClsFlg;
     private long defNumOfDaysInMth;
     private String delFlg;
     private String groupDesc;
     private String homeCntryCode;
     private String homeCrncyCode;
     private Date lchgTime;
     private String lchgUserId;
     private long numOfBackDaysAllowed;
     private long numOfFutureDaysAllowed;
     private Date rcreTime;
     private String rcreUserId;

    public SolGroupControlTableMod() {
    }

    public SolGroupControlTableMod(long solGroupId, long modId, String bankId, Date dbStatDate, Date dcClsDate, String dcClsFlg, long defNumOfDaysInMth, String delFlg, String groupDesc, String homeCntryCode, String homeCrncyCode, Date lchgTime, String lchgUserId, long numOfBackDaysAllowed, long numOfFutureDaysAllowed, Date rcreTime, String rcreUserId) {
       this.solGroupId = solGroupId;
       this.modId = modId;
       this.bankId = bankId;
       this.dbStatDate = dbStatDate;
       this.dcClsDate = dcClsDate;
       this.dcClsFlg = dcClsFlg;
       this.defNumOfDaysInMth = defNumOfDaysInMth;
       this.delFlg = delFlg;
       this.groupDesc = groupDesc;
       this.homeCntryCode = homeCntryCode;
       this.homeCrncyCode = homeCrncyCode;
       this.lchgTime = lchgTime;
       this.lchgUserId = lchgUserId;
       this.numOfBackDaysAllowed = numOfBackDaysAllowed;
       this.numOfFutureDaysAllowed = numOfFutureDaysAllowed;
       this.rcreTime = rcreTime;
       this.rcreUserId = rcreUserId;
    }
   
    public long getSolGroupId() {
        return this.solGroupId;
    }
    
    public void setSolGroupId(long solGroupId) {
        this.solGroupId = solGroupId;
    }
    public long getModId() {
        return this.modId;
    }
    
    public void setModId(long modId) {
        this.modId = modId;
    }
    public String getBankId() {
        return this.bankId;
    }
    
    public void setBankId(String bankId) {
        this.bankId = bankId;
    }
    public Date getDbStatDate() {
        return this.dbStatDate;
    }
    
    public void setDbStatDate(Date dbStatDate) {
        this.dbStatDate = dbStatDate;
    }
    public Date getDcClsDate() {
        return this.dcClsDate;
    }
    
    public void setDcClsDate(Date dcClsDate) {
        this.dcClsDate = dcClsDate;
    }
    public String getDcClsFlg() {
        return this.dcClsFlg;
    }
    
    public void setDcClsFlg(String dcClsFlg) {
        this.dcClsFlg = dcClsFlg;
    }
    public long getDefNumOfDaysInMth() {
        return this.defNumOfDaysInMth;
    }
    
    public void setDefNumOfDaysInMth(long defNumOfDaysInMth) {
        this.defNumOfDaysInMth = defNumOfDaysInMth;
    }
    public String getDelFlg() {
        return this.delFlg;
    }
    
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }
    public String getGroupDesc() {
        return this.groupDesc;
    }
    
    public void setGroupDesc(String groupDesc) {
        this.groupDesc = groupDesc;
    }
    public String getHomeCntryCode() {
        return this.homeCntryCode;
    }
    
    public void setHomeCntryCode(String homeCntryCode) {
        this.homeCntryCode = homeCntryCode;
    }
    public String getHomeCrncyCode() {
        return this.homeCrncyCode;
    }
    
    public void setHomeCrncyCode(String homeCrncyCode) {
        this.homeCrncyCode = homeCrncyCode;
    }
    public Date getLchgTime() {
        return this.lchgTime;
    }
    
    public void setLchgTime(Date lchgTime) {
        this.lchgTime = lchgTime;
    }
    public String getLchgUserId() {
        return this.lchgUserId;
    }
    
    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId;
    }
    public long getNumOfBackDaysAllowed() {
        return this.numOfBackDaysAllowed;
    }
    
    public void setNumOfBackDaysAllowed(long numOfBackDaysAllowed) {
        this.numOfBackDaysAllowed = numOfBackDaysAllowed;
    }
    public long getNumOfFutureDaysAllowed() {
        return this.numOfFutureDaysAllowed;
    }
    
    public void setNumOfFutureDaysAllowed(long numOfFutureDaysAllowed) {
        this.numOfFutureDaysAllowed = numOfFutureDaysAllowed;
    }
    public Date getRcreTime() {
        return this.rcreTime;
    }
    
    public void setRcreTime(Date rcreTime) {
        this.rcreTime = rcreTime;
    }
    public String getRcreUserId() {
        return this.rcreUserId;
    }
    
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId;
    }




}


