package com.sim.gls.jpa;
// Generated Feb 22, 2017 10:54:51 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SubGrpTableMod generated by hbm2java
 */
public class SubGrpTableMod  implements java.io.Serializable {


     private long modId;
     private String bankId;
     private String branchName;
     private String countryCode;
     private String delFlg;
     private Date firstMeetDate;
     private Date formationDate;
     private long groupId;
     private String lastOper;
     private Date lchgDate;
     private String lchgUserId;
     private long loanAccounts;
     private long maxAllowedMembers;
     private String meetFrequency;
     private String meetPlace;
     private String meetTime;
     private long noOfMembers;
     private Date nxtMeetDate;
     private double outstandingBal;
     private Date rcreTime;
     private String rcreUserId;
     private long savingAccounts;
     private double savingsAmt;
     private long solId;
     private String subGpChair;
     private String subGpRegion;
     private String subGpSecretary;
     private String subGpStatus;
     private String subGpStatusCode;
     private String subGpTreasurer;
     private String subGroupAddress;
     private String subGroupCenter;
     private String subGroupCode;
     private long subGroupId;
     private double subGroupLoans;
     private String subGroupName;
     private String subGroupPhone;
     private String subGroupVillage;
     private String subGrpAcntName;
     private String subGrpAcntNo;
     private String subGrpMgrId;
     private String subGrpRegNo;

    public SubGrpTableMod() {
    }

	
    public SubGrpTableMod(long modId, String bankId, String branchName, String countryCode, String delFlg, Date firstMeetDate, Date formationDate, long groupId, String lastOper, Date lchgDate, String lchgUserId, long loanAccounts, long maxAllowedMembers, String meetFrequency, String meetPlace, long noOfMembers, Date nxtMeetDate, double outstandingBal, Date rcreTime, String rcreUserId, long savingAccounts, double savingsAmt, long solId, String subGpRegion, String subGpStatus, String subGpStatusCode, String subGroupAddress, String subGroupCenter, String subGroupCode, long subGroupId, double subGroupLoans, String subGroupName, String subGroupPhone, String subGroupVillage, String subGrpAcntName, String subGrpAcntNo, String subGrpMgrId, String subGrpRegNo) {
        this.modId = modId;
        this.bankId = bankId;
        this.branchName = branchName;
        this.countryCode = countryCode;
        this.delFlg = delFlg;
        this.firstMeetDate = firstMeetDate;
        this.formationDate = formationDate;
        this.groupId = groupId;
        this.lastOper = lastOper;
        this.lchgDate = lchgDate;
        this.lchgUserId = lchgUserId;
        this.loanAccounts = loanAccounts;
        this.maxAllowedMembers = maxAllowedMembers;
        this.meetFrequency = meetFrequency;
        this.meetPlace = meetPlace;
        this.noOfMembers = noOfMembers;
        this.nxtMeetDate = nxtMeetDate;
        this.outstandingBal = outstandingBal;
        this.rcreTime = rcreTime;
        this.rcreUserId = rcreUserId;
        this.savingAccounts = savingAccounts;
        this.savingsAmt = savingsAmt;
        this.solId = solId;
        this.subGpRegion = subGpRegion;
        this.subGpStatus = subGpStatus;
        this.subGpStatusCode = subGpStatusCode;
        this.subGroupAddress = subGroupAddress;
        this.subGroupCenter = subGroupCenter;
        this.subGroupCode = subGroupCode;
        this.subGroupId = subGroupId;
        this.subGroupLoans = subGroupLoans;
        this.subGroupName = subGroupName;
        this.subGroupPhone = subGroupPhone;
        this.subGroupVillage = subGroupVillage;
        this.subGrpAcntName = subGrpAcntName;
        this.subGrpAcntNo = subGrpAcntNo;
        this.subGrpMgrId = subGrpMgrId;
        this.subGrpRegNo = subGrpRegNo;
    }
    public SubGrpTableMod(long modId, String bankId, String branchName, String countryCode, String delFlg, Date firstMeetDate, Date formationDate, long groupId, String lastOper, Date lchgDate, String lchgUserId, long loanAccounts, long maxAllowedMembers, String meetFrequency, String meetPlace, String meetTime, long noOfMembers, Date nxtMeetDate, double outstandingBal, Date rcreTime, String rcreUserId, long savingAccounts, double savingsAmt, long solId, String subGpChair, String subGpRegion, String subGpSecretary, String subGpStatus, String subGpStatusCode, String subGpTreasurer, String subGroupAddress, String subGroupCenter, String subGroupCode, long subGroupId, double subGroupLoans, String subGroupName, String subGroupPhone, String subGroupVillage, String subGrpAcntName, String subGrpAcntNo, String subGrpMgrId, String subGrpRegNo) {
       this.modId = modId;
       this.bankId = bankId;
       this.branchName = branchName;
       this.countryCode = countryCode;
       this.delFlg = delFlg;
       this.firstMeetDate = firstMeetDate;
       this.formationDate = formationDate;
       this.groupId = groupId;
       this.lastOper = lastOper;
       this.lchgDate = lchgDate;
       this.lchgUserId = lchgUserId;
       this.loanAccounts = loanAccounts;
       this.maxAllowedMembers = maxAllowedMembers;
       this.meetFrequency = meetFrequency;
       this.meetPlace = meetPlace;
       this.meetTime = meetTime;
       this.noOfMembers = noOfMembers;
       this.nxtMeetDate = nxtMeetDate;
       this.outstandingBal = outstandingBal;
       this.rcreTime = rcreTime;
       this.rcreUserId = rcreUserId;
       this.savingAccounts = savingAccounts;
       this.savingsAmt = savingsAmt;
       this.solId = solId;
       this.subGpChair = subGpChair;
       this.subGpRegion = subGpRegion;
       this.subGpSecretary = subGpSecretary;
       this.subGpStatus = subGpStatus;
       this.subGpStatusCode = subGpStatusCode;
       this.subGpTreasurer = subGpTreasurer;
       this.subGroupAddress = subGroupAddress;
       this.subGroupCenter = subGroupCenter;
       this.subGroupCode = subGroupCode;
       this.subGroupId = subGroupId;
       this.subGroupLoans = subGroupLoans;
       this.subGroupName = subGroupName;
       this.subGroupPhone = subGroupPhone;
       this.subGroupVillage = subGroupVillage;
       this.subGrpAcntName = subGrpAcntName;
       this.subGrpAcntNo = subGrpAcntNo;
       this.subGrpMgrId = subGrpMgrId;
       this.subGrpRegNo = subGrpRegNo;
    }
   
    public long getModId() {
        return this.modId;
    }
    
    public void setModId(long modId) {
        this.modId = modId;
    }
    public String getBankId() {
        return this.bankId;
    }
    
    public void setBankId(String bankId) {
        this.bankId = bankId;
    }
    public String getBranchName() {
        return this.branchName;
    }
    
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public String getDelFlg() {
        return this.delFlg;
    }
    
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }
    public Date getFirstMeetDate() {
        return this.firstMeetDate;
    }
    
    public void setFirstMeetDate(Date firstMeetDate) {
        this.firstMeetDate = firstMeetDate;
    }
    public Date getFormationDate() {
        return this.formationDate;
    }
    
    public void setFormationDate(Date formationDate) {
        this.formationDate = formationDate;
    }
    public long getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(long groupId) {
        this.groupId = groupId;
    }
    public String getLastOper() {
        return this.lastOper;
    }
    
    public void setLastOper(String lastOper) {
        this.lastOper = lastOper;
    }
    public Date getLchgDate() {
        return this.lchgDate;
    }
    
    public void setLchgDate(Date lchgDate) {
        this.lchgDate = lchgDate;
    }
    public String getLchgUserId() {
        return this.lchgUserId;
    }
    
    public void setLchgUserId(String lchgUserId) {
        this.lchgUserId = lchgUserId;
    }
    public long getLoanAccounts() {
        return this.loanAccounts;
    }
    
    public void setLoanAccounts(long loanAccounts) {
        this.loanAccounts = loanAccounts;
    }
    public long getMaxAllowedMembers() {
        return this.maxAllowedMembers;
    }
    
    public void setMaxAllowedMembers(long maxAllowedMembers) {
        this.maxAllowedMembers = maxAllowedMembers;
    }
    public String getMeetFrequency() {
        return this.meetFrequency;
    }
    
    public void setMeetFrequency(String meetFrequency) {
        this.meetFrequency = meetFrequency;
    }
    public String getMeetPlace() {
        return this.meetPlace;
    }
    
    public void setMeetPlace(String meetPlace) {
        this.meetPlace = meetPlace;
    }
    public String getMeetTime() {
        return this.meetTime;
    }
    
    public void setMeetTime(String meetTime) {
        this.meetTime = meetTime;
    }
    public long getNoOfMembers() {
        return this.noOfMembers;
    }
    
    public void setNoOfMembers(long noOfMembers) {
        this.noOfMembers = noOfMembers;
    }
    public Date getNxtMeetDate() {
        return this.nxtMeetDate;
    }
    
    public void setNxtMeetDate(Date nxtMeetDate) {
        this.nxtMeetDate = nxtMeetDate;
    }
    public double getOutstandingBal() {
        return this.outstandingBal;
    }
    
    public void setOutstandingBal(double outstandingBal) {
        this.outstandingBal = outstandingBal;
    }
    public Date getRcreTime() {
        return this.rcreTime;
    }
    
    public void setRcreTime(Date rcreTime) {
        this.rcreTime = rcreTime;
    }
    public String getRcreUserId() {
        return this.rcreUserId;
    }
    
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId;
    }
    public long getSavingAccounts() {
        return this.savingAccounts;
    }
    
    public void setSavingAccounts(long savingAccounts) {
        this.savingAccounts = savingAccounts;
    }
    public double getSavingsAmt() {
        return this.savingsAmt;
    }
    
    public void setSavingsAmt(double savingsAmt) {
        this.savingsAmt = savingsAmt;
    }
    public long getSolId() {
        return this.solId;
    }
    
    public void setSolId(long solId) {
        this.solId = solId;
    }
    public String getSubGpChair() {
        return this.subGpChair;
    }
    
    public void setSubGpChair(String subGpChair) {
        this.subGpChair = subGpChair;
    }
    public String getSubGpRegion() {
        return this.subGpRegion;
    }
    
    public void setSubGpRegion(String subGpRegion) {
        this.subGpRegion = subGpRegion;
    }
    public String getSubGpSecretary() {
        return this.subGpSecretary;
    }
    
    public void setSubGpSecretary(String subGpSecretary) {
        this.subGpSecretary = subGpSecretary;
    }
    public String getSubGpStatus() {
        return this.subGpStatus;
    }
    
    public void setSubGpStatus(String subGpStatus) {
        this.subGpStatus = subGpStatus;
    }
    public String getSubGpStatusCode() {
        return this.subGpStatusCode;
    }
    
    public void setSubGpStatusCode(String subGpStatusCode) {
        this.subGpStatusCode = subGpStatusCode;
    }
    public String getSubGpTreasurer() {
        return this.subGpTreasurer;
    }
    
    public void setSubGpTreasurer(String subGpTreasurer) {
        this.subGpTreasurer = subGpTreasurer;
    }
    public String getSubGroupAddress() {
        return this.subGroupAddress;
    }
    
    public void setSubGroupAddress(String subGroupAddress) {
        this.subGroupAddress = subGroupAddress;
    }
    public String getSubGroupCenter() {
        return this.subGroupCenter;
    }
    
    public void setSubGroupCenter(String subGroupCenter) {
        this.subGroupCenter = subGroupCenter;
    }
    public String getSubGroupCode() {
        return this.subGroupCode;
    }
    
    public void setSubGroupCode(String subGroupCode) {
        this.subGroupCode = subGroupCode;
    }
    public long getSubGroupId() {
        return this.subGroupId;
    }
    
    public void setSubGroupId(long subGroupId) {
        this.subGroupId = subGroupId;
    }
    public double getSubGroupLoans() {
        return this.subGroupLoans;
    }
    
    public void setSubGroupLoans(double subGroupLoans) {
        this.subGroupLoans = subGroupLoans;
    }
    public String getSubGroupName() {
        return this.subGroupName;
    }
    
    public void setSubGroupName(String subGroupName) {
        this.subGroupName = subGroupName;
    }
    public String getSubGroupPhone() {
        return this.subGroupPhone;
    }
    
    public void setSubGroupPhone(String subGroupPhone) {
        this.subGroupPhone = subGroupPhone;
    }
    public String getSubGroupVillage() {
        return this.subGroupVillage;
    }
    
    public void setSubGroupVillage(String subGroupVillage) {
        this.subGroupVillage = subGroupVillage;
    }
    public String getSubGrpAcntName() {
        return this.subGrpAcntName;
    }
    
    public void setSubGrpAcntName(String subGrpAcntName) {
        this.subGrpAcntName = subGrpAcntName;
    }
    public String getSubGrpAcntNo() {
        return this.subGrpAcntNo;
    }
    
    public void setSubGrpAcntNo(String subGrpAcntNo) {
        this.subGrpAcntNo = subGrpAcntNo;
    }
    public String getSubGrpMgrId() {
        return this.subGrpMgrId;
    }
    
    public void setSubGrpMgrId(String subGrpMgrId) {
        this.subGrpMgrId = subGrpMgrId;
    }
    public String getSubGrpRegNo() {
        return this.subGrpRegNo;
    }
    
    public void setSubGrpRegNo(String subGrpRegNo) {
        this.subGrpRegNo = subGrpRegNo;
    }




}


