package com.sim.gls.jpa;
// Generated Feb 22, 2017 10:54:51 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserCredsTblMod generated by hbm2java
 */
public class UserCredsTblMod  implements java.io.Serializable {


     private long modId;
     private RoleProfileTable roleProfileTable;
     private Date acctExpyDate;
     private long acctInactiveDays;
     private Date disabledFromDate;
     private Date disabledUptoDate;
     private Date lastAccessTime;
     private String lastOper;
     private String newUserFlg;
     private long numPwdAttempts;
     private long numPwdHistory;
     private Date pwExpyDate;
     private String pwdHistory;
     private String rcreUserId;
     private long userId;
     private String userName;
     private String userPw;

    public UserCredsTblMod() {
    }

    public UserCredsTblMod(RoleProfileTable roleProfileTable, Date acctExpyDate, long acctInactiveDays, Date disabledFromDate, Date disabledUptoDate, Date lastAccessTime, String lastOper, String newUserFlg, long numPwdAttempts, long numPwdHistory, Date pwExpyDate, String pwdHistory, String rcreUserId, long userId, String userName, String userPw) {
       this.roleProfileTable = roleProfileTable;
       this.acctExpyDate = acctExpyDate;
       this.acctInactiveDays = acctInactiveDays;
       this.disabledFromDate = disabledFromDate;
       this.disabledUptoDate = disabledUptoDate;
       this.lastAccessTime = lastAccessTime;
       this.lastOper = lastOper;
       this.newUserFlg = newUserFlg;
       this.numPwdAttempts = numPwdAttempts;
       this.numPwdHistory = numPwdHistory;
       this.pwExpyDate = pwExpyDate;
       this.pwdHistory = pwdHistory;
       this.rcreUserId = rcreUserId;
       this.userId = userId;
       this.userName = userName;
       this.userPw = userPw;
    }
    public UserCredsTblMod(long modId, RoleProfileTable roleProfileTable, Date acctExpyDate, long acctInactiveDays, Date disabledFromDate, Date disabledUptoDate, Date lastAccessTime, String lastOper, String newUserFlg, long numPwdAttempts, long numPwdHistory, Date pwExpyDate, String pwdHistory, String rcreUserId, long userId, String userName, String userPw) {
       this.modId = modId;
       this.roleProfileTable = roleProfileTable;
       this.acctExpyDate = acctExpyDate;
       this.acctInactiveDays = acctInactiveDays;
       this.disabledFromDate = disabledFromDate;
       this.disabledUptoDate = disabledUptoDate;
       this.lastAccessTime = lastAccessTime;
       this.lastOper = lastOper;
       this.newUserFlg = newUserFlg;
       this.numPwdAttempts = numPwdAttempts;
       this.numPwdHistory = numPwdHistory;
       this.pwExpyDate = pwExpyDate;
       this.pwdHistory = pwdHistory;
       this.rcreUserId = rcreUserId;
       this.userId = userId;
       this.userName = userName;
       this.userPw = userPw;
    }
   
    public long getModId() {
        return this.modId;
    }
    
    public void setModId(long modId) {
        this.modId = modId;
    }
    public RoleProfileTable getRoleProfileTable() {
        return this.roleProfileTable;
    }
    
    public void setRoleProfileTable(RoleProfileTable roleProfileTable) {
        this.roleProfileTable = roleProfileTable;
    }
    public Date getAcctExpyDate() {
        return this.acctExpyDate;
    }
    
    public void setAcctExpyDate(Date acctExpyDate) {
        this.acctExpyDate = acctExpyDate;
    }
    public long getAcctInactiveDays() {
        return this.acctInactiveDays;
    }
    
    public void setAcctInactiveDays(long acctInactiveDays) {
        this.acctInactiveDays = acctInactiveDays;
    }
    public Date getDisabledFromDate() {
        return this.disabledFromDate;
    }
    
    public void setDisabledFromDate(Date disabledFromDate) {
        this.disabledFromDate = disabledFromDate;
    }
    public Date getDisabledUptoDate() {
        return this.disabledUptoDate;
    }
    
    public void setDisabledUptoDate(Date disabledUptoDate) {
        this.disabledUptoDate = disabledUptoDate;
    }
    public Date getLastAccessTime() {
        return this.lastAccessTime;
    }
    
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }
    public String getLastOper() {
        return this.lastOper;
    }
    
    public void setLastOper(String lastOper) {
        this.lastOper = lastOper;
    }
    public String getNewUserFlg() {
        return this.newUserFlg;
    }
    
    public void setNewUserFlg(String newUserFlg) {
        this.newUserFlg = newUserFlg;
    }
    public long getNumPwdAttempts() {
        return this.numPwdAttempts;
    }
    
    public void setNumPwdAttempts(long numPwdAttempts) {
        this.numPwdAttempts = numPwdAttempts;
    }
    public long getNumPwdHistory() {
        return this.numPwdHistory;
    }
    
    public void setNumPwdHistory(long numPwdHistory) {
        this.numPwdHistory = numPwdHistory;
    }
    public Date getPwExpyDate() {
        return this.pwExpyDate;
    }
    
    public void setPwExpyDate(Date pwExpyDate) {
        this.pwExpyDate = pwExpyDate;
    }
    public String getPwdHistory() {
        return this.pwdHistory;
    }
    
    public void setPwdHistory(String pwdHistory) {
        this.pwdHistory = pwdHistory;
    }
    public String getRcreUserId() {
        return this.rcreUserId;
    }
    
    public void setRcreUserId(String rcreUserId) {
        this.rcreUserId = rcreUserId;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPw() {
        return this.userPw;
    }
    
    public void setUserPw(String userPw) {
        this.userPw = userPw;
    }




}


